### ISSUE TITLE
Enhance uuid function

### ISSUE THREAD

**Issue by peter279k** [selective-php/util#3]
Actually, the UUID has the different versions.

I think we can add the `UUIDv3` and `UUIDv5` to enhance the `uuid` function :).

@odan, do you have any thought about this :smiley:?

**Comment by odan** [comment]
I like the simplicity of the `uuid` function, because I never had a requirement to use other/more UUID versions. If I would need more, then maybe https://github.com/ramsey/uuid would be a better fit. I see multiple options for the `uuid` function:

1. Keep it as it is (UUID v4).

2. Add an optional parameter to pass a version flag.
This would blow-up the lean and clean uuid function. The cyclomatic complexity would grow and the code quality would decrease. 

3. Create a new class library for UUID's with support for multiple version.
In this case maybe https://github.com/ramsey/uuid would be a better existing and tested library.

**Comment by peter279k** [comment]
@odan, thank you for your reply. Here is my thoughts about these three options you mention:

- I agree that we can keep the `uuid` function existed.
- Yes. The optional version flag in the existed `uuid` function will be complicated and the code quality amd coverage will be decreased.
- The new `uuid` class would be great and we can use the `ramsey/uuid` for our `UUID` pakcage unit test.

In summary, I prefer the last option. That's about creating a new package named `UUID` in this org.

And using the `ramsey/uuid` package to help us to validate `UUID` values during unit tests.

What do you think about that :) ?

**Comment by odan** [comment]
> And using the ramsey/uuid package to help us to validate UUID values during unit tests.

3. )  What I tried to say was: If you need multiple UUID versions, you better use `ramsey/uuuid`. But if you don't want so many dependencies, need more power, and only need UUID v4, then the `uuid` function of this library would be good enough or even better. 

Creating a new `selective/uuid` package only makes sense if we move our `uuid()` function there.

**Comment by peter279k** [comment]
Thanks, @odan. I prefer creating new package named `selective/uuid` to keep the uuid versions methods lightweight :).

**Comment by odan** [comment]
The new "home" for the uuid function is now: https://github.com/selective-php/uuid
