### ISSUE TITLE
Making encode_json compatible with JsonSerializable

### ISSUE THREAD

**Issue by odan** [selective-php/util#4]
The function `encode_json` is not compatible with the PHP [JsonSerializable](https://www.php.net/manual/en/class.jsonserializable.php) interface.

### Example

```php
class Foo implements \JsonSerializable
{
    private $key = 'value';

    public function jsonSerialize()
    {
        return ['key' => $this->key];
    }
}

echo encode_json(new Foo());
```

### Output

```
PHP Warning:  mb_check_encoding(): Input is something other than scalar or array in util.php on line 142

PHP Catchable fatal error:  Object of class \Foo could not be converted to string
````

@peter279k Do you have any idea how to fix this issue?
If not possible, I would suggest to remove `encode_json` and `decode_json` completely.

**Comment by peter279k** [comment]
According to the [mb_check_encoding function reference](https://www.php.net/manual/en/function.mb-check-encoding.php), the first parameter is the `string` type.

And the `Foo` class is object.

I also found this is defined in the `encode_utf8`.

I think we can consider the [utf8_encode ](https://www.php.net/manual/en/function.utf8-encode.php) and [utf8_decode ](https://www.php.net/manual/en/function.utf8-decode.php)functions rather than using the `mb_convert_encoding`.

**Comment by peter279k** [comment]
Consider following approach:

- Check the `$data` is instance of  `JsonSerializable `.
- Traversal the `$data` array via `$data->jsonSerialize()`.
- Check the `$value` are `utf-8` encoding recursively, if it's not `utf-8` encoding, do encoding conversion.
- Return $data.
